[Service]
ExecStart=
ExecStart=/usr/libexec/naps3/ipp-usb-naps3 udev -path-conf-files-srch /usr/libexec/naps3/ipp-usb-conf -path-quirks-files-srch /usr/libexec/naps3/ipp-usb-quirks:/etc/ipp-usb/quirks:/usr/share/ipp-usb/quirks
